export const GAME_CONFIG = {
  FLUX_ARENA: {
    ARENA_RADIUS: 12,
    ARENA_SIDES: 8,
    PLATFORM_THICKNESS: 0.5,
    FALL_THRESHOLD: -5,
    PUSH_POWER: 10,
    PUSH_COOLDOWN_MS: 800,
    FLUX_EVENT_INTERVAL_MS: 20000,
    MATCH_DURATION_MS: 90000,
    PLAYER_SPEED: 8,
    PLAYER_MASS: 1.0,
    LINEAR_DAMPING: 0.3,
    AI_REACTION_MS: 400,
  },
  SCORING: {
    KNOCKOFF: 2,
    COMBO_BONUS: 1,
    FLUX_MASTER: 1,
    SELF_KO: -1,
  },
  UI: {
    FADE_DURATION_MS: 300,
  },
} as const;
